on:
  pull_request:
    types: [opened, synchronize]

name: Lint and Tests

jobs:
  test:
    name: Lint and Tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - run: npm ci
      - run: npm run lint
